# Generated by Django 6.0.2 on 2026-03-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la Marca')),
                ('pais', models.CharField(max_length=100, verbose_name="País d'origen")),
            ],
        ),
        migrations.CreateModel(
            name='ModelCotxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom del Model')),
                ('any_fabricacio', models.IntegerField(verbose_name='Any de fabricació')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cotxes_app.marca')),
            ],
        ),
    ]
